### PR TITLE
US_CY11_61 has been completed. Requesting to merge

### PR DESCRIPTION
**Pull request by ghost**
US_CY11_61_ErrorMessageInCalendar has been automated. Ready for review and merge

### CODE REVIEW

**Review by Jewel522 — CHANGES_REQUESTED** [review]
The code passed successfully for sales and store manager; For driver, it did not pass;
After modifying the path for errorMessage in line 311 to : "(//div[@class='alert alert-error fade in top-messages '])[2]/div"    ,  then code passed completely.
Good Job! Brandon!

**Comment by ghost** [comment]
Code adjusted and fixed. GitHub is still a bit confusing. lol Ready to merge

**Review by AERKEN — APPROVED** [review]
good job

**Review by DavidJacobsMG — APPROVED** [review]

**Review by Jewel522 — APPROVED** [review]
Excellent Job!

**Pull request merged**
